{
    "report": null,
    "template": null,
    "section": null,
    "history": [
        {
            "historyGUID": null,
            "createDate": "12/29/2015 11:37 AM ",
            "createdBy": {
                "userID": 0,
                "userGUID": "1dabf8d2-5bf4-4aac-a7a7-dc9d77ccbcb1",
                "userName": "Demo Name",
                "title": null,
                "firstName": "Gautam",
                "middleInitial": null,
                "lastName": "Kochar",
                "email": null,
                "officeEmail": null,
                "emailClosing": null,
                "directPhone": null,
                "cellPhone": null,
                "qualificationsFile": null,
                "qualificationsFileDisplayName": null,
                "qualificationsFileCoreFileGUID": null,
                "signatureFile": null,
                "signatureFileDisplayName": null,
                "signatureFileCoreFileGUID": null,
                "allowAdminsToSign": false,
                "allowFeeAssignments": false,
                "allowAppraisalReviews": false,
                "allowEvaluations": false,
                "certifiedHUDFHA": null,
                "certifiedVA": null,
                "designations": null,
                "expertise": null,
                "employeeNumber": null,
                "licenses": null,
                "insurances": null,
                "forms": null,
                "createdTS": null,
                "modifiedTS": null,
                "coverageAreas": null,
                "teams": null,
                "isEnabled": false,
                "isEnvProfessional": false
            },
            "updateComment": null,
            "section": {
                "sectionGUID": "6fbceca3-521a-43e5-9c45-ed1794b6e6f1",
                "sectionData": {"html":"<span>{{contentValues.sectionTitle00}}</span>","contentValues":{"sectionTitle00":"The Project has been undeveloped throughout its history."}},
                "sectionTitle": null,
                "sectionNumber": null,
                "subSections": null,
                "languageLibraries": null,
                "historyLibrary": null,
                "comments": null,
                "attachmentReference": null
            }
        },
        {
            "historyGUID": null,
            "createDate": "12/29/2014 10:17 AM ",
            "createdBy": {
                "userID": 0,
                "userGUID": "6fbceca3-521a-43e5-9c45-ed1664b8e6f3",
                "userName": "Demo Name",
                "title": null,
                "firstName": "Ankit",
                "middleInitial": null,
                "lastName": "Raja",
                "email": null,
                "officeEmail": null,
                "emailClosing": null,
                "directPhone": null,
                "cellPhone": null,
                "qualificationsFile": null,
                "qualificationsFileDisplayName": null,
                "qualificationsFileCoreFileGUID": null,
                "signatureFile": null,
                "signatureFileDisplayName": null,
                "signatureFileCoreFileGUID": null,
                "allowAdminsToSign": false,
                "allowFeeAssignments": false,
                "allowAppraisalReviews": false,
                "allowEvaluations": false,
                "certifiedHUDFHA": null,
                "certifiedVA": null,
                "designations": null,
                "expertise": null,
                "employeeNumber": null,
                "licenses": null,
                "insurances": null,
                "forms": null,
                "createdTS": null,
                "modifiedTS": null,
                "coverageAreas": null,
                "teams": null,
                "isEnabled": false,
                "isEnvProfessional": false
            },
            "updateComment": null,
            "section": {
                "sectionGUID": "6fbceca3-521a-43e5-9c45-ed1794b6e6f1",
                "sectionData": {"html":"<span>{{contentValues.sectionTitle00}}</span>","contentValues":{"sectionTitle00":"EMG performed a Phase I Environmental Site Assessment, that included on-site observations of the accessible areas of the ProjectName (the Project), on OnSiteDate, 2008.  The Project is located at ProjectAddress in ProjectCity, ProjectState ProjectZIP, and consists of approximately ProjectAcres-acres."}},
                "sectionTitle": null,
                "sectionNumber": null,
                "subSections": null,
                "languageLibraries": null,
                "historyLibrary": null,
                "comments": null,
                "attachmentReference": null
            }
        },
        {
            "historyGUID": null,
            "createDate": "12/29/2015 11:37 AM ",
            "createdBy": {
                "userID": 0,
                "userGUID": "6fbceca3-521a-43e5-9c45-ed1664b8e6f3",
                "userName": "Demo Name",
                "title": null,
                "firstName": "Shantnu",
                "middleInitial": null,
                "lastName": "Kumar",
                "email": null,
                "officeEmail": null,
                "emailClosing": null,
                "directPhone": null,
                "cellPhone": null,
                "qualificationsFile": null,
                "qualificationsFileDisplayName": null,
                "qualificationsFileCoreFileGUID": null,
                "signatureFile": null,
                "signatureFileDisplayName": null,
                "signatureFileCoreFileGUID": null,
                "allowAdminsToSign": false,
                "allowFeeAssignments": false,
                "allowAppraisalReviews": false,
                "allowEvaluations": false,
                "certifiedHUDFHA": null,
                "certifiedVA": null,
                "designations": null,
                "expertise": null,
                "employeeNumber": null,
                "licenses": null,
                "insurances": null,
                "forms": null,
                "createdTS": null,
                "modifiedTS": null,
                "coverageAreas": null,
                "teams": null,
                "isEnabled": false,
                "isEnvProfessional": false
            },
            "updateComment": null,
            "section": {
                "sectionGUID": "6fbceca3-521a-43e5-9c45-ed1794b6e6f1",
                "sectionData": {"html":"<span>{{contentValues.sectionTitle00}}</span>","contentValues":{"sectionTitle00":"The Project, originally constructed in XXXX, is currently a retail building retail shopping center multi-family apartment building multi-family apartment complex warehouse building commercial office facility single-family residence hotel manufactured home community.  Current facility operations include the operations and maintenance of a XXXX. "}},
                "sectionTitle": null,
                "sectionNumber": null,
                "subSections": null,
                "languageLibraries": null,
                "historyLibrary": null,
                "comments": null,
                "attachmentReference": null
            }
        },
        {
            "historyGUID": null,
            "createDate": "12/29/2015 11:37 AM ",
            "createdBy": {
                "userID": 0,
                "userGUID": "6fbceca3-521a-43e5-9c45-ed1664b8e6f3",
                "userName": "Demo Name",
                "title": null,
                "firstName": "Prateek",
                "middleInitial": null,
                "lastName": null,
                "email": null,
                "officeEmail": null,
                "emailClosing": null,
                "directPhone": null,
                "cellPhone": null,
                "qualificationsFile": null,
                "qualificationsFileDisplayName": null,
                "qualificationsFileCoreFileGUID": null,
                "signatureFile": null,
                "signatureFileDisplayName": null,
                "signatureFileCoreFileGUID": null,
                "allowAdminsToSign": false,
                "allowFeeAssignments": false,
                "allowAppraisalReviews": false,
                "allowEvaluations": false,
                "certifiedHUDFHA": null,
                "certifiedVA": null,
                "designations": null,
                "expertise": null,
                "employeeNumber": null,
                "licenses": null,
                "insurances": null,
                "forms": null,
                "createdTS": null,
                "modifiedTS": null,
                "coverageAreas": null,
                "teams": null,
                "isEnabled": false,
                "isEnvProfessional": false
            },
            "updateComment": null,
            "section": {
                "sectionGUID": "6fbceca3-521a-43e5-9c45-ed1794b6e6f1",
                "sectionData": {"html":"<span>{{contentValues.sectionTitle00}}</span>","contentValues":{"sectionTitle00":"The following summarizes the independent conclusions representing EMG's best professional judgment based on information and data available to us during the course of this assignment.  Factual information regarding operations, conditions, and test data provided by the Client, owner, or their representative has been assumed to be correct and complete."}},
                "sectionTitle": null,
                "sectionNumber": null,
                "subSections": null,
                "languageLibraries": null,
                "historyLibrary": null,
                "comments": null,
                "attachmentReference": null
            }
        }
    ],
    "message": null,
    "comments": null,
    "historyLibraries": null,
    "templates": null,
    "sectionData": null,
    "appendices": null,
    "appendix": null,
    "commentTypes": null
}