{
    "report": null,
    "template": null,
    "section": null,
    "history": null,
    "message": null,
    "comments": null,
    "historyLibraries": null,
    "reportTemplate": null,
    "sectionData": null,
    "appendices": null,
    "appendix": null,
    "commentTypes": null,
    "tableOfContent": {
        "hasNarrative": false,
        "hasComments": false,
        "comments": [],
        "updatedBy": {
            "userID": 0,
            "userGUID": "bbc8bb95-f8d0-42aa-b053-00f187134f16",
            "firstName": "Developer",
            "middleInitial": null,
            "lastName": "User",
            "companyGUID": "cd024ac2-f962-472f-acf1-1dc4238c321e",
            "officeGUID": "5d96e57b-5571-4914-88b3-ce07d0c592bf"
        },
        "reportGUID": "b1b0e8dc-2960-11e6-95e5-0e29ed3d2a45",
        "clickable": false,
        "sectionNumber": "",
        "isCommentsAddressed": false,
        "sectionID": 0,
        "updatedDate": "06-09-2016 05:28:13 AM EDT",
        "sections": [{
            "hasNarrative": true,
            "hasComments": false,
            "comments": [],
            "hasPhotos": false,
            "clickable": false,
            "sectionNumber": "",
            "isCommentsAddressed": false,
            "sectionID": 4,
            "sections": [],
            "sectionName": "Verizon Wireless Project Description",
            "sectionGUID": "9bc28599-dd48-11e5-b5c1-0e29ed3d2a45",
            "sectionData": {
                "contentValues": {
                    "tagData": ["Describe what the subject property currently is & describe what Verizon plans to do."],
                    "sectionTitle0": "Verizon Wireless Project Description",
                    "ckEditData": {
                        "div1": ""
                    }
                }
            },
            "isAppendix": false,
            "appendixTools": [],
            "isVisibleInToc": false,
            "html": "<div><h3 class='border-bottom text-capitalize'>{{contentValues.sectionTitle0}}<div class='pull-right top-margin-xs bottom-margin-xs btn-group'></div><div class='clearfix'></div></h3></div><div last-updated-by updated-date='updatedDate' updated-by='updatedBy' sec-id='secId'></div><tag-with-dashes></tag-with-dashes><div class='boxCK'><span class='editCK'>edit</span><div id='ckEdit' class='textCK' ng-model='contentValues.ckEditData.div1'></div></div>",
            "isGeneralInfo": false
			}]
        "sectionName": "",
        "isAppendix": false,
        "appendixTools": [],
        "isVisibleInToc": true,
        "html": "",
        "isGeneralInfo": false
    },
    "comment": null,
    "sections": null,
    "defaults": null,
    "project": {
        "projectID": 0,
        "name": "Edr Order Test",
        "companyID": 0,
        "finalDueDate": null,
        "draftDueDate": null,
        "client": null,
        "locations": null,
        "siteContact": null,
        "accessParties": null,
        "notification": null,
        "comments": null,
        "projectGUID": "0874b6d4-4dc7-49b5-a100-eddb468c186f",
        "companyGUID": null,
        "generalInfo": null,
        "attachments": null,
        "inputFile": null,
        "mortgageBroker": null,
        "reports": null,
        "totalReports": 0,
        "numberOfFinalReports": 0
    },
    "location": {
        "locationGUID": null,
        "categories": null,
        "propertyNumber": "",
        "name": "",
        "address": "",
        "address1": "Chunabhatti",
        "address2": "",
        "city": "Pune",
        "state": "UT",
        "zip": null,
        "county": "",
        "latitude": 39.32098,
        "longitude": -111.093731,
        "acreage": "",
        "numBuildings": "",
        "transactionTypeID": 0,
        "reports": null,
        "siteContact": {
            "name": null,
            "phone": null,
            "fax": null,
            "email": null
        },
        "country": "US",
        "transactionTypeGUID": null,
        "propertyTypeGUID": null,
        "propertyID": 0,
        "propertyName": "Kachara Patti",
        "elevation": 0,
        "elevationUnits": null,
        "contactName": null,
        "contactEmail": null,
        "contactPhone": null,
        "contactFax": null,
        "notes": null,
        "dataSource": null,
        "dataSourceKey": null,
        "propertyGuid": "b1b0366c-2960-11e6-95e5-0e29ed3d2a45",
        "projectGuid": null,
        "propertyType": null,
        "transactionType": null,
        "geocodeSource": null
    },
    "reportDetails": {
        "reportGuid": "b1b0e8dc-2960-11e6-95e5-0e29ed3d2a45",
        "projectGuid": null,
        "templateID": 0,
        "libraryID": 0,
        "projectNumber": null,
        "poNumber": null,
        "fee": null,
        "reportID": 0,
        "taskedCompanyID": 0,
        "statusID": 0,
        "createDate": null,
        "reportOutputSetupID": 0,
        "reportOutputSetupGuid": null,
        "tocSetupID": 0,
        "transmittalSetupID": 0,
        "coverTemplateID": 0,
        "languageLibraryID": 2642,
        "propertyID": 0,
        "outToBid": false,
        "templateGUID": null,
        "taskedCompanyGUID": "cd024ac2-f962-472f-acf1-1dc4238c321e",
        "languageLibraryGUID": "1dd1ed9d-e1c9-11e5-886c-0eddda3124c5",
        "reportStatusGuid": "726cd04a-9791-11e5-8226-0e29ed3d2a45",
        "reportStatus": "Work Order Created",
        "templateVersionGUID": null,
        "reportTypeGuid": null,
        "reportType": "Phase I ESA",
        "propertyNumber": null,
        "propertyName": null,
        "propertyName": null,
        "address": null,
        "city": null,
        "state": null,
        "zipCode": null,
        "signatures": null,
        "generalInfo": null,
        "propertyGuid": null,
        "projectDueDate": null,
        "county": null,
        "clientCompany": null,
        "consultantCompany": null,
        "property": null,
        "projectName": null,
        "siteAssessor": null,
        "seniorReviewer": null,
        "siteID": "A0119849",
        "reportStatusAbbreviation": "WO",
        "final": false,
        "isDeactivated": false,
        "isLocked": false
    },
    "prepopulatedTableData": null,
    "sortEnum": null
}
