{
	"users": [{
		"userGUID": "123",
		"userName": "User A",
		"title": "",
		"firstName": "",
		"middleInitial": "",
		"lastName": "",
		"isEnabled": "",
		"email": "",
		"officeEmail": "",
		"emailClosing": "",
		"directPhone": "",
		"cellPhone": "",
		"qualificationsFile": "",
		"signatureFile": "",
		"isEnvProfessional": true,
		"allowAdminsToSign": true,
		"allowFeeAssignments": true,
		"allowAppraisalReviews": true,
		"allowEvaluations": true,
		"certifiedHUDFHA": true,
		"certifiedVA": true,
		"designations": "",
		"expertise": "",
		"licenses": [{
			"userLicenseGUID": "123",
			"userGUID": "123",
			"licenseState": "CT",
			"licenseNumber": "1234",
			"expirationDate": "07-22-2015 08:01:16 AM",
			"licenseType": "",
			"status": "",
			"licenseFilePath": "",
			"isVerified": true
		}],
		"insurances": [{
			"userInsuranceGUID": "123",
			"userGUID": "123",
			"carrier": "",
			"amount": 1000000.00,
			"expirationDate": "07-22-2015 08:01:16 AM",
			"insuranceDocumentFilePath": ""
		}],
		"forms": [{
			"userFormGUID": "123",
			"userGUID": "123",
			"formType": "",
			"filePath": "",
			"isEnabled": true,
			"fileName": "",
			"fileDescription": ""
		}],
		"coverageAreas": [{
			"userCoverageAreaGUID": "123",
			"userGUID": "123",
			"state": "CT",
			"county": "New Haven"
		}],
		"teams": [{
			"teamGUID": "A0F5E294-B497-4C16-8FA4-526C9413530F",
			"name": "Team 1",
			"description": "Team of xyz",
			"companyGUID": "A0F5E294-B497-4C16-8FA4-526C9413530F",
			"officeGUID": "A0F5E294-B497-4C16-8FA4-526C9413530F",
			"isEnabled": true
		}]
	},
	{
		"userGUID": "234",
		"userName": "User B",
		"title": "",
		"firstName": "User",
		"middleInitial": "",
		"lastName": "B",
		"isEnabled": "",
		"email": "",
		"officeEmail": "",
		"emailClosing": "",
		"directPhone": "",
		"cellPhone": "",
		"qualificationsFile": "",
		"signatureFile": "",
		"isEnvProfessional": true,
		"allowAdminsToSign": true,
		"allowFeeAssignments": true,
		"allowAppraisalReviews": true,
		"allowEvaluations": true,
		"certifiedHUDFHA": true,
		"certifiedVA": true,
		"designations": "",
		"expertise": "",
		"licenses": [{
			"userLicenseGUID": "234",
			"userGUID": "234",
			"licenseState": "CT",
			"licenseNumber": "1234",
			"expirationDate": "07-22-2015 08:01:16 AM",
			"licenseType": "",
			"status": "",
			"licenseFilePath": "",
			"isVerified": true
		}],
		"insurances": [{
			"userInsuranceGUID": "234",
			"userGUID": "234",
			"carrier": "",
			"amount": 1000000.00,
			"expirationDate": "07-22-2015 08:01:16 AM",
			"insuranceDocumentFilePath": ""
		}],
		"forms": [{
			"userFormGUID": "234",
			"userGUID": "234",
			"formType": "",
			"filePath": "",
			"isEnabled": true,
			"fileName": "",
			"fileDescription": ""
		}],
		"coverageAreas": [{
			"userCoverageAreaGUID": "234",
			"userGUID": "234",
			"state": "CT",
			"county": "New Haven"
		}],
		"teams": [{
			"teamGUID": "A0F5E294-B497-4C16-8FA4-526C9413530F",
			"name": "Team 1",
			"description": "Team of xyz",
			"companyGUID": "A0F5E294-B497-4C16-8FA4-526C9413530F",
			"officeGUID": "A0F5E294-B497-4C16-8FA4-526C9413530F",
			"isEnabled": true
		}]
	},
	{
		"userGUID": "345",
		"userName": "User C",
		"title": "",
		"firstName": "User",
		"middleInitial": "",
		"lastName": "C",
		"isEnabled": "",
		"email": "",
		"officeEmail": "",
		"emailClosing": "",
		"directPhone": "",
		"cellPhone": "",
		"qualificationsFile": "",
		"signatureFile": "",
		"isEnvProfessional": true,
		"allowAdminsToSign": true,
		"allowFeeAssignments": true,
		"allowAppraisalReviews": true,
		"allowEvaluations": true,
		"certifiedHUDFHA": true,
		"certifiedVA": true,
		"designations": "",
		"expertise": "",
		"licenses": [{
			"userLicenseGUID": "345",
			"userGUID": "345",
			"licenseState": "CT",
			"licenseNumber": "1234",
			"expirationDate": "07-22-2015 08:01:16 AM",
			"licenseType": "",
			"status": "",
			"licenseFilePath": "",
			"isVerified": true
		}],
		"insurances": [{
			"userInsuranceGUID": "345",
			"userGUID": "345",
			"carrier": "",
			"amount": 1000000.00,
			"expirationDate": "07-22-2015 08:01:16 AM",
			"insuranceDocumentFilePath": ""
		}],
		"forms": [{
			"userFormGUID": "345",
			"userGUID": "345",
			"formType": "",
			"filePath": "",
			"isEnabled": true,
			"fileName": "",
			"fileDescription": ""
		}],
		"coverageAreas": [{
			"userCoverageAreaGUID": "345",
			"userGUID": "345",
			"state": "CT",
			"county": "New Haven"
		}],
		"teams": [{
			"teamGUID": "A0F5E294-B497-4C16-8FA4-526C9413530F",
			"name": "Team 1",
			"description": "Team of xyz",
			"companyGUID": "A0F5E294-B497-4C16-8FA4-526C9413530F",
			"officeGUID": "A0F5E294-B497-4C16-8FA4-526C9413530F",
			"isEnabled": true
		}]
	},
	{
		"userGUID": "456",
		"userName": "User D",
		"title": "",
		"firstName": "User",
		"middleInitial": "",
		"lastName": "D",
		"isEnabled": "",
		"email": "",
		"officeEmail": "",
		"emailClosing": "",
		"directPhone": "",
		"cellPhone": "",
		"qualificationsFile": "",
		"signatureFile": "",
		"isEnvProfessional": true,
		"allowAdminsToSign": true,
		"allowFeeAssignments": true,
		"allowAppraisalReviews": true,
		"allowEvaluations": true,
		"certifiedHUDFHA": true,
		"certifiedVA": true,
		"designations": "",
		"expertise": "",
		"licenses": [{
			"userLicenseGUID": "456",
			"userGUID": "456",
			"licenseState": "CT",
			"licenseNumber": "1234",
			"expirationDate": "07-22-2015 08:01:16 AM",
			"licenseType": "",
			"status": "",
			"licenseFilePath": "",
			"isVerified": true
		}],
		"insurances": [{
			"userInsuranceGUID": "456",
			"userGUID": "456",
			"carrier": "",
			"amount": 1000000.00,
			"expirationDate": "07-22-2015 08:01:16 AM",
			"insuranceDocumentFilePath": ""
		}],
		"forms": [{
			"userFormGUID": "456",
			"userGUID": "456",
			"formType": "",
			"filePath": "",
			"isEnabled": true,
			"fileName": "",
			"fileDescription": ""
		}],
		"coverageAreas": [{
			"userCoverageAreaGUID": "456",
			"userGUID": "456",
			"state": "CT",
			"county": "New Haven"
		}],
		"teams": [{
			"teamGUID": "A0F5E294-B497-4C16-8FA4-526C9413530F",
			"name": "Team 1",
			"description": "Team of xyz",
			"companyGUID": "A0F5E294-B497-4C16-8FA4-526C9413530F",
			"officeGUID": "A0F5E294-B497-4C16-8FA4-526C9413530F",
			"isEnabled": true
		}]
	},
	{
		"userGUID": "567",
		"userName": "User E",
		"title": "",
		"firstName": "User",
		"middleInitial": "",
		"lastName": "E",
		"isEnabled": "",
		"email": "",
		"officeEmail": "",
		"emailClosing": "",
		"directPhone": "",
		"cellPhone": "",
		"qualificationsFile": "",
		"signatureFile": "",
		"isEnvProfessional": true,
		"allowAdminsToSign": true,
		"allowFeeAssignments": true,
		"allowAppraisalReviews": true,
		"allowEvaluations": true,
		"certifiedHUDFHA": true,
		"certifiedVA": true,
		"designations": "",
		"expertise": "",
		"licenses": [{
			"userLicenseGUID": "567",
			"userGUID": "567",
			"licenseState": "CT",
			"licenseNumber": "1234",
			"expirationDate": "07-22-2015 08:01:16 AM",
			"licenseType": "",
			"status": "",
			"licenseFilePath": "",
			"isVerified": true
		}],
		"insurances": [{
			"userInsuranceGUID": "567",
			"userGUID": "567",
			"carrier": "",
			"amount": 1000000.00,
			"expirationDate": "07-22-2015 08:01:16 AM",
			"insuranceDocumentFilePath": ""
		}],
		"forms": [{
			"userFormGUID": "567",
			"userGUID": "567",
			"formType": "",
			"filePath": "",
			"isEnabled": true,
			"fileName": "",
			"fileDescription": ""
		}],
		"coverageAreas": [{
			"userCoverageAreaGUID": "567",
			"userGUID": "567",
			"state": "CT",
			"county": "New Haven"
		}],
		"teams": [{
			"teamGUID": "A0F5E294-B497-4C16-8FA4-526C9413530F",
			"name": "Team 1",
			"description": "Team of xyz",
			"companyGUID": "A0F5E294-B497-4C16-8FA4-526C9413530F",
			"officeGUID": "A0F5E294-B497-4C16-8FA4-526C9413530F",
			"isEnabled": true
		}]
	}]
}