{
	"reports" : [{
			"reportType" : "PhaseI",
			"reportTypeGuid" : "b6103d7a-98d7-11e5-8226-0e29ed3d2a45",
			"reportGuid" : "A0F5E294-B497-4C16-8FA4-526C9413530F",
			"reportStatus" : "Draft",
			"propertyNumber" : "1234567",
			"propertyName" : "NEW PROJECT FOR TESTING JSON",
			"address" : "261 Mayfield Dr. APt.11",
			"state" : "CT",
			"city" : "Trumbull",
			"zipCode" : "",
			"statusID" : 0,
			"templateGUID" : "bd97fb60-666e-470e-8753-807f4cba99f7",
			"signatures" : [{
					"templateSignatureGuid" : " e249a20e-48b8-4a10-98e0-ccc6d7d8f401",
					"signType" : "Signoff",
					"signOffType" : "SeniorReviewer",
					"pmonly" : false,
					"eponly" : true,
					"hideable" : false,
					"digitalSignatureInPrintedReport" : true,
					"signed" : false,
					"showInPrintedReport" : true,
					"createdTS" : " 07-22-2015 08:01:16 AM",
					"orderIndex" : 1,
					"certificationText" : "",
					"signOffUser" : {
						"userGUID": "06D73813-64D3-49CB-88DB-013E13F96F11",
                        "userName": "Sunil Tambe",
                        "title": "Mandatory Signoff",
                        "email": "STambe",
                        "cellPhone": "5326414152"
					},
					"signedOnBehalfOfUser" : {},
					"signedForUser" : {}
				}, 
                {
					"templateSignatureGuid" : " e249a20e-48b8-4a10-98e0-ccc6d7d8f401",
					"signType" : "Signoff",
					"signOffType" : "SEC Name",
					"pmonly" : false,
					"eponly" : true,
					"hideable" : false,
					"digitalSignatureInPrintedReport" : true,
					"signed" : false,
					"showInPrintedReport" : true,
					"createdTS" : " 07-22-2015 08:01:16 AM",
					"orderIndex" : 1,
					"certificationText" : "",
					"signOffUser" : {
						"userGUID": "06D73813-64D3-49CB-88DB-013E13F96F12",
                        "userName": "G K",
                        "title": "Mandatory Signoff",
                        "email": "gk@compumatrice.com",
                        "cellPhone": "5326414152"
					},
					"signedOnBehalfOfUser" : {},
					"signedForUser" : {}
				},
                    {
					"templateSignatureGuid" : "e249a20e-48b8-4a10-98e0-ccc6d7d8f401",
                    "reportSignOffGuid": "",
					"signType" : "Certification",
					"signOffType" : "Certification",
					"pmonly" : false,
					"eponly" : true,
					"hideable" : false,
					"digitalSignatureInPrintedReport" : true,
					"signed" : false,
					"showInPrintedReport" : true,
					"createdTS" : " 07-22-2015 08:01:16 AM",
					"orderIndex" : 1,
					"certificationText" : "I declare that, to the best of my professional knowledge and belief..",
					"signOffUser" : {
						"userGUID": "00000000-0000-0000-0000-000000000001",
                        "userName": "John Doe",
                        "title": "",
                        "email": "",
                        "cellPhone": ""
					},
					"signedOnBehalfOfUser" : {},
					"signedForUser" : {}
				}, {
					"templateSignatureGuid" : " e249a20e-48b8-4a10-98e0-ccc6d7d8f401",
					"signType" : "Certification",
					"signOffType" : "Certification",
					"pmonly" : false,
					"eponly" : true,
					"hideable" : false,
					"digitalSignatureInPrintedReport" : true,
					"signed" : false,
					"showInPrintedReport" : true,
					"createdTS" : " 07-22-2015 08:01:16 AM",
					"orderIndex" : 1,
					"certificationText" : "I declare that, to the best of my professional knowledge and belief, I meet the definition of Environmental Professional as defined in 40 CFR Part 312. I have the specific qualifications based on education, training, and experience to assess a property of the nature, history, and setting of the subject property. I have developed and performed the all appropriate inquiries in conformance with the standards and practices set forth in 40 CFR Part 312.",
					"signOffUser" : {},
					"signedOnBehalfOfUser" : {},
					"signedForUser" : {}
				}, {
					"templateSignatureGuid" : " e249a20e-48b8-4a10-98e0-ccc6d7d8f401",
					"signType" : " SiteAssessor",
					"signOffType" : " SiteAssessor",
					"pmonly" : false,
					"eponly" : false,
					"hideable" : false,
					"digitalSignatureInPrintedReport" : true,
					"signed" : false,
					"showInPrintedReport" : true,
					"createdTS" : " 07-22-2015 08:01:16 AM",
					"orderIndex" : 1,
					"certificationText" : "",
					"signOffUser" : {},
					"signedOnBehalfOfUser" : {},
					"signedForUser" : {}
				}
			]
		}, {
			"reportType" : "PhaseII",
			"reportTypeGuid" : "b6103d7a-98d7-11e5-8226-0e29ed3d2a46",
			"reportGuid" : "A0F5E294-B497-4C16-8FA4-526C9413531F",
			"reportStatus" : "Draft",
			"propertyNumber" : "E07934",
			"propertyName" : "Environmental",
			"address" : "Dogwood Estates, LLC Site 4201-4205 Falls Road Baltimore",
			"state" : "",
			"city" : "Maryland",
			"zipCode" : "21211",
			"statusID" : 0,
			"templateGUID" : "bd97fb60-666e-470e-8753-807f4cba99f7",
			"signatures" : [{
					"templateSignatureGuid" : " e249a20e-48b8-4a10-98e0-ccc6d7d8f401",
					"signType" : "Signoff ",
					"signOffType" : "SeniorReviewer",
					"pmonly" : false,
					"eponly" : false,
					"hideable" : false,
					"digitalSignatureInPrintedReport" : true,
					"signed" : false,
					"showInPrintedReport" : true,
					"createdTS" : " 07-22-2015 08:01:16 AM",
					"orderIndex" : 1,
					"certificationText" : "aaa",
					"signOffUser" : {
						"userGUID" : "A0F5E294-B497-4C16-8FA4-526C9413534F",
						"userName" : "",
						"title" : "Senior Reviewer",
						"email" : "jdoe@edrnet.com",
						"phone" : "555-555-5555"
					},
					"signedOnBehalfOfUser" : {},
					"signedForUser" : {}
				}, {
					"templateSignatureGuid" : " e249a20e-48b8-4a10-98e0-ccc6d7d8f401",
					"signType" : "SiteAssessor",
					"signOffType" : "SiteAssessor",
					"pmonly" : false,
					"eponly" : false,
					"hideable" : false,
					"digitalSignatureInPrintedReport" : true,
					"signed" : false,
					"showInPrintedReport" : true,
					"createdTS" : " 07-22-2015 08:01:16 AM",
					"orderIndex" : 1,
					"certificationText" : "",
					"signOffUser" : {
						"userGUID" : " A0F5E294-B497-4C16-8FA4-526C9413533F ",
						"userName" : " John P Doe",
						"title" : "Site Assessor",
						"phone" : "555-555-5555"
					},
					"signedOnBehalfOfUser" : {},
					"signedForUser" : {}
				}
			]
		},
         {
			"reportType" : "PhaseI",
			"reportTypeGuid" : "b6103d7a-98d7-11e5-8226-0e29ed3d2a45",
			"reportGuid" : "A0F5E294-B497-4C16-8FA4-526C9413532F",
			"reportStatus" : "Draft",
			"propertyNumber" : "456789",
			"propertyName" : "NEW PROJECT FOR TESTING JSON",
			"address" : "267 Mayfield Dr. APt.11",
			"state" : "CT",
			"city" : "Trumbull",
			"zipCode" : "",
			"statusID" : 0,
			"templateGUID" : "bd97fb60-666e-470e-8753-807f4cba99f7",
			"signatures" : [{
					"templateSignatureGuid" : " e249a20e-48b8-4a10-98e0-ccc6d7d8f401",
					"signType" : "Signoff ",
					"signOffType" : "SeniorReviewer",
					"pmonly" : false,
					"eponly" : false,
					"hideable" : false,
					"digitalSignatureInPrintedReport" : true,
					"signed" : false,
					"showInPrintedReport" : true,
					"createdTS" : " 07-22-2015 08:01:16 AM",
					"orderIndex" : 1,
					"certificationText" : "",
					"signOffUser" : {                        
                        "userGUID": "A0F5E294-B497-4C16-8FA4-526C9413530F",
                        "userName": "Kevin Kozar",
                        "title": "Senior Reviewer",
                        "email": "",
                        "cellPhone": ""					
					},
					"signedOnBehalfOfUser" : {},
					"signedForUser" : {}
				}, {
					"templateSignatureGuid" : " e249a20e-48b8-4a10-98e0-ccc6d7d8f401",
					"signType" : "Certification",
					"signOffType" : "Certification",
					"pmonly" : false,
					"eponly" : true,
					"hideable" : false,
					"digitalSignatureInPrintedReport" : true,
					"signed" : false,
					"showInPrintedReport" : true,
					"createdTS" : " 07-22-2015 08:01:16 AM",
					"orderIndex" : 1,
					"certificationText" : "",
					"signOffUser" : {},
					"signedOnBehalfOfUser" : {},
					"signedForUser" : {}
				}
			]
		}
	]
}